### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sonicviz** [e4rthdog/captureFS#1]
Hey Elias, 

I reposted my suggestions here as per your request.

>>Do you think it would be better if i saved the last path as default every time you close the app?

Yes, so it gets updated each time you change it, so the default will always be the last used path. 
At the moment, it seems to default to desktop. 

Thanks, 
Paul

From: Elias Stassinos 
Sent: Monday, 6 June 2022 10:31 PM
To: paul
Subject: Re: CaptureFS

Hi Paul!

I am happy that you found it interesting. All these things are feasible i think. I can take a look at them.

Please i would appreciate if you just report it here: https://github.com/e4rthdog/captureFS/issues

Also include some more details. What should i do about the "current path?" I f you click the icon on the desktop i am not sure what current path is.

Do you think it would be better if i saved the last path as default every time you close the app?

As far the file type option and intervals its clear i will look at them.

Thank you!

Elias Stassinos

On Mon, Jun 6, 2022 at 2:23 AM <[paul> wrote:
Hey Elias,
 
I’ve been having a play with https://www.estassinos.com/capturefs/ and it’s very useful, thanks. 
 
I have a couple of questions, based on using it for a while.
 
Is it possible to get the path dialog to default to where the current path is set when you open it? Makes it faster to change, than having to renavigate the file structure from the root every time. 
Is it possible to change the screenshot type to jpg (with configurable quality)? PNG takes up a lot of space, and the difference with JPG is negligible I’ve found. Big savings on HDD space!
Save intervals you set as default for next time?

**Comment by e4rthdog** [comment]
Everything is implemented. Just uploaded the new version to flightsim.to -> https://flightsim.to/file/3764/capturefs

Enjoy and please report back any issues.

**Comment by sonicviz** [comment]
Awesome, ty!
